[project]
name = "logtap"
version = "0.1.0"
description = "Log file analyzer and monitor for debugging sessions"
readme = "README.md"
authors = [
    { name = "Fredrik Angelsen", email = "fredrikangelsen@gmail.com" }
]
requires-python = ">=3.12"
classifiers = ["Private :: Do Not Upload"]
dependencies = []

[project.scripts]
logtap = "logtap:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.basedpyright]
typeCheckingMode = "standard"
pythonVersion = "3.12"
pythonPlatform = "Linux"
include = ["src/**/*.py"]

[tool.ruff]
line-length = 120
include = ["src/**/*.py"]
