[project]
name = "webtap"
version = "0.1.0"
description = "Terminal-based web page inspector for AI debugging sessions"
readme = "README.md"
authors = [
    { name = "Fredrik Angelsen", email = "fredrikangelsen@gmail.com" }
]
requires-python = ">=3.12"
classifiers = ["Private :: Do Not Upload"]
dependencies = [
    "beautifulsoup4>=4.13.5",
    "duckdb>=1.3.2",
    "fastapi>=0.116.1",
    "pyyaml>=6.0.2",
    "replkit2",
    "requests>=2.32.4",
    "uvicorn>=0.35.0",
    "websocket-client>=1.8.0",
]

[project.scripts]
webtap = "webtap:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
replkit2 = { path = "../../../replkit2", editable = true }
