[project]
name = "webtap"
version = "0.1.0"
description = "Terminal-based web page inspector for AI debugging sessions"
readme = "README.md"
authors = [
    { name = "Fredrik Angelsen", email = "fredrikangelsen@gmail.com" }
]
requires-python = ">=3.12"
classifiers = ["Private :: Do Not Upload"]
dependencies = []

[project.scripts]
webtap = "webtap:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
