[project]
name = "termtap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Fredrik Angelsen", email = "fredrikangelsen@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "fastmcp>=2.11.2",
    "replkit2",
    "uvicorn>=0.35.0",
]

[project.scripts]
termtap = "termtap:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
replkit2 = { path = "../../../replkit2", editable = true }

[tool.ruff]
line-length = 120
include = ["src/**/*.py", "tests/**/*.py"]
exclude = ["**/__pycache__", "**/.venv", "**/build", "**/dist"]

[tool.basedpyright]
typeCheckingMode = "standard"
pythonVersion = "3.12"
pythonPlatform = "Linux"
include = ["src/**/*.py"]
exclude = ["**/__pycache__", "**/.venv", "**/build", "**/dist"]
