[project]
name = "termtap"
version = "0.3.0"
description = "Process-native tmux session manager with MCP support"
readme = "README.md"
authors = [{ name = "Fredrik Angelsen", email = "fredrikangelsen@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "fastmcp>=2.11.2",
    "replkit2",
    "uvicorn>=0.35.0",
]

[project.scripts]
termtap = "termtap:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
replkit2 = { path = "../../../replkit2", editable = true }
