[project]
name = "termtap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fredrik Angelsen", email = "fredrikangelsen@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
termtap = "termtap:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
