[default]
dir = "."
hover_patterns = ["ERROR", "FAIL", "WARNING"]

[frontend]
dir = "./frontend"
start = "npm run dev"

[backend]
dir = "./backend"
start = "uv run python server.py"
env = { PYTHONPATH = ".", DEBUG = "1" }